### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless - I used optipng (`optipng -o7 -strip all *.png`).

### CODE REVIEW

**Comment by Noaaan** [comment]
Reducing the file size of all the assets with about 30-40% seems like a really interesting change. I am however in the middle of re-working a lot of the assets. Merging this now would simply lead this to be re-done multiple times.
If you could give me more details with the software you are using, and the configuration of it, I would happily do this process myself when the time is appropriate.

**Comment by K0-RR** [comment]
Firstly I used the command-line tool "optipng" (the command is in the pr desc) but then wafflecoffee from ConsistencyPlus pointed out that "oxipng" is better. My command for it was `oxipng -arvD -o max --strip all --fix PATH/TO/RESOURCES`.
https://github.com/shssoichiro/oxipng

EDIT. There is also the -Z parameter (used instead "D"). It enables the Zopfli algorithm - better compression but way slower. I tested some repositories with -Z and without it. The differences: ~7% better compression but 4-100x slower. For a MC mod, it shouldn't take more than 2 minutes (or 20 sec without -Z) with a mid-end laptop but I tested it with a 300 MB repository - 5 minutes with the default algorithm and... 20 hours with Zopfli so I don't advise using it on a huge repo.

**Comment by K0-RR** [comment]
Or you can use imgbot.net. The compression will be slightly worse but still good and it doesn't require setting up aside of enabling it and merging pr.

**Comment by K0-RR** [comment]
>I am however in the middle of re-working a lot of the assets

Forget it, this was meant to be asked on the More Gems repo after I saw that your mod has deepslate variants. Sorry for the ping!

**Pull request closed without merging**
