### PR TITLE
Update zh_cn.json

### LINKED ISSUE #166: Update to Chinese translate
I created a fork for updating Chinese translations. Modified some of the original translations and added new ones. Now you can check it and decide which part to keep.
Thanks for your work, this mod is really great!

### PR DESCRIPTION
**Pull request by DSRoie**
Updated the old Chinese translation for the new version of the mod

### CODE REVIEW

**Comment by Noaaan** [comment]
Looks good! Do note that I recently finished up the update for 1.19.4, which adds a lot more translations.
If you wish I could sync up the missing translation keys between this and english, to make it easier to see what isn't currently translated.
Even if you do not wish to translate the rest, your contribution is much appreciated. Thank you for taking your time to do so!

**Comment by DSRoie** [comment]
> Looks good! Do note that I recently finished up the update for 1.19.4, which adds a lot more translations. If you wish I could sync up the missing translation keys between this and english, to make it easier to see what isn't currently translated. Even if you do not wish to translate the rest, your contribution is much appreciated. Thank you for taking your time to do so!

I'm glad to do that. It would be nice to have those translation keys

**Comment by Noaaan** [comment]
Bumping this. I realize in hindsight I messed up the branch a bit, sorry. This should now be fixed.

**Comment by nageih** [comment]
the new keys aren't translated,I am translating the mod,in about a couple weeks I'll create pr

**Comment by Noaaan** [comment]
Bumping this translation, as it has not been updated in a while

**Pull request closed without merging**
