### PR TITLE
Localization processing

### PR DESCRIPTION
**Pull request by YeziMoanan**
I have localized the text of these two classes and added them to the English lang file for Chinese players to translate easily

### CODE REVIEW

**Comment by Noaaan** [comment]
Is there any need for this? These are internal names for attributes, and are to my knowledge only visible when debugging code. I am not sure if they show up anywhere else.
For the attributes themselves most of them are vanilla, or a part of Additional Entity Attributes. If you wish to translate those, I suggest contributing to that repo directly: https://github.com/DaFuqs/AdditionalEntityAttributes

**Comment by YeziMoanan** [comment]
These are the files that my friend sent me while searching for these texts. I am not sure if these will appear in front of players in the game. They are responsible for translating the texts, and I only localize the possible files they sent. If you don't think they are needed, just cancel. Sorry

**Comment by nageih** [comment]
At least in the game "magic protection" is visible, which means it makes sense to translate it, I don't know if anything else is visible

**Comment by nageih** [comment]
C4FYJ}BRCY10WEX)RW9FEBX

**Comment by nageih** [comment]
I've learned that this AdditionalEntityAttributes is built-in to the mod file, I didn't see it before

**Pull request closed without merging**
