### PR TITLE
Added translation for anvils

### PR DESCRIPTION
**Pull request by Oscienet**

### CODE REVIEW

**Comment by Noaaan** [comment]
Looking good so far. I am still adding more items, so please check back later once I manage to push those commits

**Comment by Noaaan** [comment]
I like how you had the manganese and kyber anvil added, even though I have not committed them until now 😄 
Just gonna add some missing textures and will probably merge.

**Comment by Oscienet** [comment]
Oupsie, i've only copied these strings from the former version of the en_us lang, in which they already were added by DeatHunter👀

**Comment by Oscienet** [comment]
If anything, i just checked this version of ru_ru lang, bc was afraid of syntaxis issues, and it works fine

**Pull request merged**
